name: Sentinel
schemes:
  Sentinel:
    build:
      targets:
        Sentinel: all
        SentinelTests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - Sentinel
      targets: 
        - SentinelTests
      commandLineArguments:
        "-isRunningUnitTests YES": true
options:
  bundleIdPrefix: uk.co.cerihughes
packages:
  Madog:
    url: https://github.com/cerihughes/Madog
    from: 5.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
targets:
  Sentinel:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      INFOPLIST_FILE: Resources/Info.plist
      DEVELOPMENT_TEAM: Y56955G4Q8
    sources:
      - Source
      - Resources
    dependencies:
      - package: Madog
      - package: SnapKit
    postCompileScripts:
      - script: swiftlint
        name: Swift Lint
  SentinelTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources: Tests
    dependencies:
      - target: Sentinel