name: Build and test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        xcode: [15.4]
        include:
          - ios: 17.5
            xcode: 15.4
          - ipad: "iPad (10th generation)"
            xcode: 15.4

    runs-on: macos-14

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}

      # Install dependencies
      - run: brew install xcodegen || true
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: xcodegen
      - run: xcodebuild clean test -project Sentinel.xcodeproj -scheme Sentinel -clonedSourcePackagesDirPath SPM -resultBundlePath coverage.xcresult -destination "OS=${{ matrix.ios }},name=${{ matrix.ipad }}" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            xcode: true
            xcode_archive_path: ${{ github.workspace }}/coverage.xcresult
            verbose: true
